apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: simple-web-server-pvc
spec:
  storageClassName: {{ .Values.storage.storageClassName }}
  accessModes: {{ .Values.storage.accessModes }}
  resources:
    requests:
      storage: {{ .Values.storage.capacity }}